openapi: 3.0.2
info:
  title: 'Person for Biometric'
  version: '1.0.0'
paths:
  /people/{iin}/:
    get:
      operationId: retrievePeople
      description: 'Get person by IIN'
      parameters:
      - name: iin
        in: path
        required: true
        description: A unique value identifying this person.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People'
          description: 'successful operation'
      tags:
      - people
  /people/:
    post:
      operationId: createPeople
      description: 'Create a person'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/People'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/People'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/People'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People'
          description: 'successful operation'
      tags:
      - people
components:
  schemas:
    People:
      type: object
      properties:
        iin:
          type: string
          maxLength: 12
        age:
          type: integer
          readOnly: true
      required:
      - iin
