# Generated by Django 4.0.1 on 2022-01-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('iin', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
